@startuml
start
repeat :Create Entities
  switch (entity_type?)
  case ( Bundle )
    :Create Bundle;

    if (Create Charge?) then (yes)
      :Create Charge;
      :Create ProductToChargeRelationship;
    else (no)
    endif

    if (Create Relationship?) then (yes)
      :Create ProductToProductRelationship;
    else (no)
    endif

  case ( Package ) 
    :Create Package;

    if (Create Charge?) then (yes)
      :Create Charge;
      :Create ProductToChargeRelationship;
    else (no)
    endif

    if (Create Relationship?) then (yes)
      :Create ProductToProductRelationship;
    else (no)
    endif

  case ( Component )
    :Create Component;
    if (Create Charge?) then (yes)
      :Create Charge;
      :Create ProductToChargeRelationship;
    else (no)
    endif

    if (Create Relationship?) then (yes)
      :Create ProductToProductRelationship;
    else (no)
    endif

  case ( Promotion )
    :Create Promotion;
    if (Create Charge?) then (yes)
      :Create Charge;
      :Create ProductToChargeRelationship;
    else (no)
    endif

    if (Create Relationship?) then (yes)
      :Create ProductToProductRelationship;
    else (no)
    endif

  case ( Charge )
    :Create Charge;
    :Create ProductToChargeRelationship;

    if (Create Relationship?) then (yes)
      :Create ProductToChargeRelationship;
    else (no)
    endif

  case ( Discount )
    :Create Discount;

    if (Create Relationship?) then (yes)
      :Create ProductToChargeRelationship;
    else (no)
    endif

  endswitch

repeat while (MinChildEntities > 0) is (yes)
  ->no;
  stop
@enduml