openapi: 3.0.0
info:
  title: Web Application API
  version: 1.0.0
  description: API for a web application managing user interactions and conversations.
servers:
  - url: http://localhost:8000
    description: Local development server
paths:
  /:
    get:
      summary: Home page
      description: Renders the home page or login page based on authentication status and conversation state.
      responses:
        '200':
          description: HTML page rendered.
          content:
            text/html:
              schema:
                type: string
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: false
          description: Access token for user authentication.
        - in: query
          name: ai_name
          schema:
            type: string
          required: false
          description: The name of the AI to interact with.
        - in: query
          name: new_conversation
          schema:
            type: string
          required: false
          description: Flag to start a new conversation.
        - in: query
          name: conversation_id
          schema:
            type: string
          required: false
          description: The ID of the conversation.
    post:
      summary: Submit message
      description: Processes the user's message, managing authentication, conversation state, and response generation.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: User input for conversation.
                ai_name:
                  type: string
                  description: The name of the AI to interact with.
                new_conversation:
                  type: string
                  description: Flag to start a new conversation.
                conversation_id:
                  type: string
                  description: The ID of the conversation.
      responses:
        '200':
          description: HTML page rendered with conversation update.
          content:
            text/html:
              schema:
                type: string
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: false
          description: Access token for user authentication.
  /call_prompt_tool:
    post:
      summary: Call a prompt tool function
      description: Executes a prompt tool function based on the provided parameters, for authenticated users only.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                function_name:
                  type: string
                  description: The prompt tool function to execute.
                prompt_template:
                  type: string
                  description: The prompt template for generating the prompt.
                # Additional parameters as needed by the prompt tool function
      responses:
        '200':
          description: JSON response with generated prompt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated_prompt:
                    type: string
                    description: The prompt generated by the prompt tool.
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
  /call_ai_tool:
    post:
      summary: Interact with an AI tool
      description: Allows authenticated users to interact with a specified AI tool, sending and receiving data.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                function_name:
                  type: string
                  description: The AI tool function to call.
                ai_name:
                  type: string
                  description: The name of the AI to interact with.
                conversation_id:
                  type: string
                  description: The ID of the conversation.
                # Additional parameters as needed by the AI tool function
      responses:
        '200':
          description: JSON response with AI tool's output.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The response from the AI tool.
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.

  /conversation_history:
    get:
      summary: Fetch conversation history
      description: Retrieves the history of a conversation for an authenticated user.
      responses:
        '200':
          description: JSON response containing conversation history.
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id:
                    type: string
                    description: The ID of the conversation.
                  conversation_history:
                    type: array
                    items:
                      type: string
                    description: A list of messages in the conversation history.
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
        - in: query
          name: ai_name
          schema:
            type: string
          required: false
          description: The name of the AI involved in the conversation.
        - in: query
          name: conversation_id
          schema:
            type: string
          required: true
          description: The ID of the conversation whose history is to be retrieved.
  /list_conversations:
    get:
      summary: List all conversations
      description: Lists all conversation IDs for a given AI name for an authenticated user.
      responses:
        '200':
          description: JSON response with list of conversation IDs.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: A list of conversation IDs.
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
        - in: query
          name: ai_name
          schema:
            type: string
          required: false
          description: The name of the AI whose conversations are to be listed.
  /conversations:
    get:
      summary: Display conversations
      description: Renders a page displaying conversation details for an authenticated user.
      responses:
        '200':
          description: HTML page showing conversation details.
          content:
            text/html:
              schema:
                type: string
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
        - in: query
          name: ai_name
          schema:
            type: string
          required: false
          description: The name of the AI involved in the conversation.
        - in: query
          name: conversation_id
          schema:
            type: string
          required: false
          description: The ID of the conversation to display.
  /conversations/{ai_name}/{conversation_id}:
    delete:
      summary: Delete a conversation
      description: Deletes a specific conversation for an authenticated user.
      responses:
        '303':
          description: Redirects to the conversations list page after deletion.
      parameters:
        - in: path
          name: ai_name
          schema:
            type: string
          required: true
          description: The name of the AI involved in the conversation.
        - in: path
          name: conversation_id
          schema:
            type: string
          required: true
          description: The ID of the conversation to be deleted.
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
  /get_ai_settings:
    get:
      summary: Get AI settings
      description: Retrieves settings for an AI instance for an authenticated user.
      responses:
        '200':
          description: JSON response with AI settings.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ai_instructions:
                    type: string
                    description: Instructions for using the AI.
                  ai_tool_instructions:
                    type: string
                    description: Instructions for using AI tools.
      parameters:
        - in: cookie
          name: access_token
          schema:
            type: string
          required: true
          description: Access token for user authentication.
        - in: query
          name: ai_name
          schema:
            type: string
          required: true
          description: The name of the AI for which settings are being requested.
        - in: query
          name: conversation_id
          schema:
            type: string
          required: false
          description: The ID of the conversation.
